spring:
  profiles:
    active: pg,mail
server:
  port: 8081
token:
  recover-clean-in-sec: "3600"
default-parse-period: # in sec
  steam-item: 777600 # 216 часов  update steam_item set parse_period = 777600 where id in (select id from steam_item where parse_period = 604800)
  active-name: 21600 # 6 часов
scheduled: # in ms
  default: "25000"
  active-name: "1000"
  parse-queue: "10001"
  steam-item: "10000"
  lot-profit: "10000"
  telegram-bot: "300000"
  actual-currency-relation: "7200000"
initialize:
  admin: true
  user: true
default-user:
  login: "admin"
  password: "admin"
  email: "admin-user-42-user-admin@gmail.com"
  full-name: "Админ Админович Админов"
generators:
  message: false
  active-name: false
  real-active-name: false
  parse-queue: false
  lot-with-steam-items: false
truncate-table:
  active-name: false
  parse-queue: false
  lot: false
  lot-sticker: false
  steam-item: false
queue:
  max-attempts: 5
telegram-enabled: false