spring:
  profiles:
    active: pg,mail
server:
  port: 8081
token:
  recover-clean-in-sec: "3600"
default-parse-period: # in sec
  steam-item: 3600
  active-name: 180
scheduled: # in ms
  default: "25000"
  active-name: "1000"
  parse-queue: "5000"
  steam-item: "1000"
  lot-profit: "10000"
  actual-currency-relation: "3600000"
initialize:
  admin: true
  user: true
default-user:
  login: "admin"
  password: "admin"
  email: "admin-user-42-user-admin@gmail.com"
  full-name: "Админ Админович Админов"
generators:
  message: false
  active-name: false
  real-active-name: true
  parse-queue: false
  lot-with-steam-items: false
truncate-table:
  active-name: false
  parse-queue: true
  lot: true
  lot-sticker: true
  steam-item: true
queue:
  max-attempts: 5